"""Repository interfaces.

``get`` raises when absent; ``find`` returns None. They are never mixed --
half of all null-handling bugs in this family come from a ``get`` that quietly
returned nothing.

No method returns an unbounded list.
"""

from __future__ import annotations

from datetime import date, datetime
from typing import Any, Protocol


class UnitOfWorkPort(Protocol):
    """One use case, one transaction."""

    def __enter__(self) -> UnitOfWorkPort: ...
    def __exit__(self, *args: Any) -> None: ...
    def flush(self) -> None: ...


class UserRepository(Protocol):
    def get(self, id: str) -> Any: ...
    def find_by_phone(self, phone: str) -> Any | None: ...
    def create(self, *, id: str, phone: str, locale: str, full_name: str | None) -> Any: ...
    def roles_of(self, user_id: str) -> list[str]: ...
    def grant_role(self, user_id: str, role_code: str) -> None: ...
    def save(self, row: Any) -> Any: ...


class OtpRepository(Protocol):
    def create(self, **fields: Any) -> Any: ...
    def find_active(self, phone: str, *, at: datetime) -> Any | None: ...
    def count_recent(self, phone: str, *, since: datetime) -> int: ...
    def save(self, row: Any) -> Any: ...


class RefreshTokenRepository(Protocol):
    def create(self, **fields: Any) -> Any: ...
    def find_by_hash(self, token_hash: str) -> Any | None: ...
    def revoke_all_for_user(self, user_id: str, *, at: datetime) -> int: ...
    def save(self, row: Any) -> Any: ...


class GeographyRepository(Protocol):
    def list_districts(self, *, province_id: str | None = None) -> list[Any]: ...
    def list_villages(self, district_id: str, *, limit: int, offset: int) -> list[Any]: ...
    def list_stations(self, village_id: str) -> list[Any]: ...
    def get_station(self, id: str) -> Any: ...
    def search_places(self, term: str, *, limit: int) -> list[Any]: ...
    def nearby_stations(
        self, latitude: Any, longitude: Any, *, radius_m: int, limit: int
    ) -> list[Any]: ...
    def get_destination(self, id: str) -> Any: ...
    def destinations_reachable_from(self, station_id: str) -> list[Any]: ...
    def snapshot_version(self) -> str: ...


class RouteRepository(Protocol):
    def get(self, id: str) -> Any: ...
    def find_serving(self, origin_station_id: str, destination_id: str) -> list[Any]: ...
    def stops_of(self, route_id: str) -> list[Any]: ...
    def list_templates(self) -> list[Any]: ...
    def save(self, row: Any) -> Any: ...


class FareRepository(Protocol):
    def find_rule(
        self,
        *,
        route_id: str,
        ride_kind: str,
        from_sequence: int,
        to_sequence: int,
        vehicle_type_code: str | None,
        on: date,
    ) -> Any | None: ...


class TripRepository(Protocol):
    def get(self, id: str) -> Any: ...
    def find_by_number(self, number: str) -> Any | None: ...
    def search(
        self,
        *,
        route_ids: list[str],
        departure_from: datetime,
        departure_to: datetime,
        ride_kind: str | None,
        limit: int,
    ) -> list[Any]: ...
    def create(self, **fields: Any) -> Any: ...
    def save(self, row: Any) -> Any: ...
    def stops_of(self, trip_id: str) -> list[Any]: ...
    def active_for_driver(self, driver_id: str) -> Any | None: ...


class TripSeatRepositoryPort(Protocol):
    def list_for_trip(self, trip_id: str) -> list[Any]: ...
    def count_available(self, trip_id: str) -> int: ...
    def lock_available(self, trip_id: str, seat_count: int) -> list[Any]: ...
    def reserve(self, seats: list[Any], booking_id: str) -> list[Any]: ...
    def release_for_booking(self, booking_id: str) -> int: ...
    def occupy_for_booking(self, booking_id: str) -> int: ...


class BookingRepository(Protocol):
    def get(self, id: str) -> Any: ...
    def flush(self) -> None: ...
    def find_by_number(self, number: str) -> Any | None: ...
    def list_for_passenger(self, passenger_id: str, *, limit: int, offset: int) -> list[Any]: ...
    def list_for_trip(self, trip_id: str) -> list[Any]: ...
    def count_active_for_passenger(self, passenger_id: str) -> int: ...
    def create(self, **fields: Any) -> Any: ...
    def save(self, row: Any) -> Any: ...


class DriverRepository(Protocol):
    def get(self, id: str) -> Any: ...
    def find_by_user(self, user_id: str) -> Any | None: ...
    def available_for(self, *, limit: int) -> list[Any]: ...
    def documents_of(self, driver_id: str) -> list[Any]: ...
    def save(self, row: Any) -> Any: ...


class VehicleRepository(Protocol):
    def get(self, id: str) -> Any: ...
    def primary_for_driver(self, driver_id: str) -> Any | None: ...
    def save(self, row: Any) -> Any: ...


class WalletRepository(Protocol):
    def get_or_create(self, driver_id: str, currency: str) -> Any: ...
    def append(self, **fields: Any) -> Any: ...
    def save(self, row: Any) -> Any: ...


class PaymentRepository(Protocol):
    def find_for_booking(self, booking_id: str) -> Any | None: ...
    def create(self, **fields: Any) -> Any: ...
    def save(self, row: Any) -> Any: ...


class RatingRepository(Protocol):
    def find(self, trip_id: str, rater_user_id: str, ratee_user_id: str) -> Any | None: ...
    def create(self, **fields: Any) -> Any: ...


class IdempotencyRepository(Protocol):
    def find(self, key: str, endpoint: str) -> Any | None: ...
    def remember(self, **fields: Any) -> Any: ...
