"""The error-code registry.

A code is a contract: it is referenced by translations, by API consumers and by
support staff. Codes are registered here exactly once; raising an unregistered
code fails a test. Changing the meaning of an existing code is a breaking
change -- add a new one instead.

Format: <AGGREGATE>_<CONDITION>.
"""

from __future__ import annotations

from typing import Final

# -- validation ----------------------------------------------------------
VALIDATION_FAILED: Final = "VALIDATION_FAILED"
PHONE_INVALID: Final = "PHONE_INVALID"
LOCALE_UNSUPPORTED: Final = "LOCALE_UNSUPPORTED"

# -- auth / identity -----------------------------------------------------
OTP_INVALID: Final = "OTP_INVALID"
OTP_EXPIRED: Final = "OTP_EXPIRED"
OTP_ATTEMPTS_EXCEEDED: Final = "OTP_ATTEMPTS_EXCEEDED"
OTP_RATE_LIMITED: Final = "OTP_RATE_LIMITED"
OTP_ALREADY_CONSUMED: Final = "OTP_ALREADY_CONSUMED"
TOKEN_INVALID: Final = "TOKEN_INVALID"
TOKEN_EXPIRED: Final = "TOKEN_EXPIRED"
REFRESH_TOKEN_REVOKED: Final = "REFRESH_TOKEN_REVOKED"
USER_NOT_FOUND: Final = "USER_NOT_FOUND"
USER_SUSPENDED: Final = "USER_SUSPENDED"
PERMISSION_DENIED: Final = "PERMISSION_DENIED"

# -- geography -----------------------------------------------------------
PROVINCE_NOT_FOUND: Final = "PROVINCE_NOT_FOUND"
DISTRICT_NOT_FOUND: Final = "DISTRICT_NOT_FOUND"
VILLAGE_NOT_FOUND: Final = "VILLAGE_NOT_FOUND"
VILLAGE_CODE_TAKEN: Final = "VILLAGE_CODE_TAKEN"
STATION_NOT_FOUND: Final = "STATION_NOT_FOUND"
STATION_DISABLED: Final = "STATION_DISABLED"
DESTINATION_NOT_FOUND: Final = "DESTINATION_NOT_FOUND"
DESTINATION_DISABLED: Final = "DESTINATION_DISABLED"
DESTINATION_CYCLE: Final = "DESTINATION_CYCLE"

# -- import --------------------------------------------------------------
IMPORT_FILE_UNREADABLE: Final = "IMPORT_FILE_UNREADABLE"
IMPORT_COLUMN_MISSING: Final = "IMPORT_COLUMN_MISSING"
IMPORT_ROW_INVALID: Final = "IMPORT_ROW_INVALID"
IMPORT_DUPLICATE_DETECTED: Final = "IMPORT_DUPLICATE_DETECTED"
IMPORT_ALREADY_COMMITTED: Final = "IMPORT_ALREADY_COMMITTED"
IMPORT_NOT_PREVIEWED: Final = "IMPORT_NOT_PREVIEWED"

# -- routes / pricing ----------------------------------------------------
ROUTE_NOT_FOUND: Final = "ROUTE_NOT_FOUND"
ROUTE_DISABLED: Final = "ROUTE_DISABLED"
ROUTE_NOT_RESOLVABLE: Final = "ROUTE_NOT_RESOLVABLE"
ROUTE_STOPS_OUT_OF_ORDER: Final = "ROUTE_STOPS_OUT_OF_ORDER"
ROUTE_TEMPLATE_SCOPE_EMPTY: Final = "ROUTE_TEMPLATE_SCOPE_EMPTY"
FARE_NOT_CONFIGURED: Final = "FARE_NOT_CONFIGURED"
FARE_NEGATIVE: Final = "FARE_NEGATIVE"

# -- supply --------------------------------------------------------------
DRIVER_NOT_FOUND: Final = "DRIVER_NOT_FOUND"
DRIVER_NOT_APPROVED: Final = "DRIVER_NOT_APPROVED"
DRIVER_SUSPENDED: Final = "DRIVER_SUSPENDED"
DRIVER_OFFLINE: Final = "DRIVER_OFFLINE"
DRIVER_ALREADY_ON_TRIP: Final = "DRIVER_ALREADY_ON_TRIP"
DRIVER_DOCUMENTS_INCOMPLETE: Final = "DRIVER_DOCUMENTS_INCOMPLETE"
DRIVER_ALREADY_REGISTERED: Final = "DRIVER_ALREADY_REGISTERED"
DOCUMENT_NOT_FOUND: Final = "DOCUMENT_NOT_FOUND"
DOCUMENT_TYPE_UNKNOWN: Final = "DOCUMENT_TYPE_UNKNOWN"
DOCUMENT_REJECTION_REASON_REQUIRED: Final = "DOCUMENT_REJECTION_REASON_REQUIRED"
VEHICLE_NOT_FOUND: Final = "VEHICLE_NOT_FOUND"
VEHICLE_SUSPENDED: Final = "VEHICLE_SUSPENDED"
VEHICLE_PLATE_TAKEN: Final = "VEHICLE_PLATE_TAKEN"
VEHICLE_CAPACITY_INVALID: Final = "VEHICLE_CAPACITY_INVALID"

# -- trips ---------------------------------------------------------------
TRIP_NOT_FOUND: Final = "TRIP_NOT_FOUND"
TRIP_INVALID_TRANSITION: Final = "TRIP_INVALID_TRANSITION"
TRIP_SEATS_UNAVAILABLE: Final = "TRIP_SEATS_UNAVAILABLE"
TRIP_CAPACITY_EXCEEDED: Final = "TRIP_CAPACITY_EXCEEDED"
TRIP_DEPARTED: Final = "TRIP_DEPARTED"
TRIP_CANCELLED: Final = "TRIP_CANCELLED"
TRIP_NO_DRIVER_AVAILABLE: Final = "TRIP_NO_DRIVER_AVAILABLE"
TRIP_DRIVER_ALREADY_ASSIGNED: Final = "TRIP_DRIVER_ALREADY_ASSIGNED"

# -- bookings ------------------------------------------------------------
BOOKING_NOT_FOUND: Final = "BOOKING_NOT_FOUND"
BOOKING_INVALID_TRANSITION: Final = "BOOKING_INVALID_TRANSITION"
BOOKING_ALREADY_CANCELLED: Final = "BOOKING_ALREADY_CANCELLED"
BOOKING_NOT_CANCELLABLE: Final = "BOOKING_NOT_CANCELLABLE"
BOOKING_VERIFICATION_FAILED: Final = "BOOKING_VERIFICATION_FAILED"
BOOKING_LIMIT_REACHED: Final = "BOOKING_LIMIT_REACHED"
BOOKING_SEAT_COUNT_INVALID: Final = "BOOKING_SEAT_COUNT_INVALID"
BOOKING_STOPS_OUT_OF_ORDER: Final = "BOOKING_STOPS_OUT_OF_ORDER"

# -- money ---------------------------------------------------------------
PAYMENT_NOT_FOUND: Final = "PAYMENT_NOT_FOUND"
PAYMENT_ALREADY_COLLECTED: Final = "PAYMENT_ALREADY_COLLECTED"
COMMISSION_RATE_INVALID: Final = "COMMISSION_RATE_INVALID"
WALLET_NOT_FOUND: Final = "WALLET_NOT_FOUND"
WALLET_INSUFFICIENT_BALANCE: Final = "WALLET_INSUFFICIENT_BALANCE"
SETTLEMENT_INVALID_TRANSITION: Final = "SETTLEMENT_INVALID_TRANSITION"

# -- ratings / support ---------------------------------------------------
RATING_OUT_OF_RANGE: Final = "RATING_OUT_OF_RANGE"
RATING_ALREADY_SUBMITTED: Final = "RATING_ALREADY_SUBMITTED"
RATING_TRIP_NOT_COMPLETED: Final = "RATING_TRIP_NOT_COMPLETED"
TICKET_NOT_FOUND: Final = "TICKET_NOT_FOUND"
TICKET_CLOSED: Final = "TICKET_CLOSED"

# -- platform ------------------------------------------------------------
SETTING_NOT_FOUND: Final = "SETTING_NOT_FOUND"
SETTING_TYPE_INVALID: Final = "SETTING_TYPE_INVALID"
IDEMPOTENCY_KEY_REUSED: Final = "IDEMPOTENCY_KEY_REUSED"
CONCURRENT_MODIFICATION: Final = "CONCURRENT_MODIFICATION"
RATE_LIMITED: Final = "RATE_LIMITED"
SEQUENCE_EXHAUSTED: Final = "SEQUENCE_EXHAUSTED"
STORAGE_UNAVAILABLE: Final = "STORAGE_UNAVAILABLE"
SMS_DELIVERY_FAILED: Final = "SMS_DELIVERY_FAILED"
PUSH_DELIVERY_FAILED: Final = "PUSH_DELIVERY_FAILED"
INTERNAL_ERROR: Final = "INTERNAL_ERROR"


def _registry() -> frozenset[str]:
    return frozenset(
        value
        for name, value in globals().items()
        if name.isupper() and not name.startswith("_") and isinstance(value, str)
    )


REGISTERED_CODES: Final[frozenset[str]] = _registry()


def is_registered(code: str) -> bool:
    return code in REGISTERED_CODES
