import SwiftUI

// The single registration point: each route and the screen that shows it.
//
// Feature agents do not edit this file. A feature replaces its placeholder
// (Features/<Feature>/<Feature>View.swift), keeping the type name and an
// `init()` with no arguments, and it appears here, in the sidebar and in the
// iPhone's tabs.

extension Route {
    @MainActor @ViewBuilder
    var destination: some View {
        switch self {
        case .commandCentre: CommandCentreView()
        case .dashboard: DashboardView()
        case .dispatch: DispatchView()
        case .trips: TripsView()
        case .liveRequests: LiveRequestsView()
        case .bookings: BookingsView()
        case .passengers: PassengersView()
        case .drivers: DriversView()
        case .driverApprovals: DriverApprovalsView()
        case .vehicles: VehiclesView()
        case .vehicleApprovals: VehicleApprovalsView()
        case .payouts: PayoutsView()
        case .support: SupportView()
        case .finance: FinanceView()
        case .audit: AuditView()
        case .settings: SettingsView()
        }
    }
}
