"""route template intermediate stops

Revision ID: 5f76dd65710a
Revises: 15fd484f424f
Created: 2026-08-29 02:28:25.947873

Rollback note: route template intermediate stops
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '5f76dd65710a'
down_revision: str | None = '15fd484f424f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('intermediate_destination_ids', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route_templates', schema=None) as batch_op:
        batch_op.drop_column('intermediate_destination_ids')

    # ### end Alembic commands ###
